/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

/*
* 游戏初始化配置;
*/
export default class GameConfig {
    static width: number = 1280;
    static height: number = 720;
    static scaleMode: string = "fixedauto";
    static screenMode: string = "horizontal";
    static alignV: string = "middle";
    static alignH: string = "center";
    static startScene: any = "";
    static sceneRoot: string = "";
    static debug: boolean = false;
    static stat: boolean = false;
    static physicsDebug: boolean = false;
    static exportSceneToJson: boolean = true;
    static isTest: boolean = false;
    static logDebug: boolean = false;
}